<?php
declare(strict_types=1);

return [
    'skill' => [
        'nameBase' => 'my-skill',
        'nameDateSuffix' => true,
        'name' => 'my-skill',
        'description' => 'Describe when an AI agent should activate this skill. Agentic systems compare the user\'s request to this text to decide if the skill is relevant—list concrete situations, topics, or example questions (e.g. "Use when the user asks about our onboarding process or needs a visual overview of X"). The canvas holds the knowledge; description is the trigger.',
        'author' => '',
        'version' => '1.0',
        'tags' => '',
    ],

    'canvas' => [
        'minNodeWidth' => 160,
        'minNodeHeight' => 60,
        'minScale' => 0.08,
        'maxScale' => 5,
        'fitPadding' => 80,
        'nodeFocusPadding' => 12,
    ],

    'unsaved' => [
        'confirmDiscard' => 'Du har ändringar som inte exporterats. Fortsätt utan att spara?',
        'beforeUnload' => 'Du har ändringar som inte exporterats.',
    ],

    'edges' => [
        'strokeWidth' => 2,
        'color' => '#0077bc',
        'style' => 'curve',
        'markerStart' => 'none',
        'markerEnd' => 'arrow',
    ],

    'nodes' => [
        'markdown' => [
            'width' => 720,
            'height' => 600,
            'minWidth' => 160,
            'maxWidth' => 1200,
            'minHeight' => 120,
            'maxHeight' => 1600,
            'fileDir' => 'nodes',
            'fileExt' => 'md',
        ],
        'mermaid' => [
            'width' => 500,
            'height' => 600,
            'minWidth' => 160,
            'maxWidth' => 1400,
            'minHeight' => 120,
            'maxHeight' => 1600,
            'fileDir' => 'diagrams',
            'fileExt' => 'mmd',
        ],
        'plantuml' => [
            'width' => 500,
            'height' => 600,
            'minWidth' => 160,
            'maxWidth' => 1400,
            'minHeight' => 120,
            'maxHeight' => 1600,
            'fileDir' => 'diagrams',
            'fileExt' => 'puml',
        ],
        'image' => [
            'width' => 400,
            'minWidth' => 120,
            'maxWidth' => 1200,
            'fileDir' => 'images',
        ],
        'label' => [
            'fontSize' => 28,
            'color' => '#0077bc',
            'minFontSize' => 10,
            'maxFontSize' => 120,
            'minWidth' => 80,
            'maxWidth' => 2000,
        ],
        'note' => [
            'width' => 220,
            'minWidth' => 140,
            'maxWidth' => 480,
            'minHeight' => 120,
            'maxHeight' => 480,
            'color' => '#fff9a8',
            'fontSize' => 14,
        ],
        'drawio' => [
            'width' => 480,
            'minWidth' => 200,
            'maxWidth' => 1200,
            'fileDir' => 'diagrams',
        ],
        'bpmn' => [
            'width' => 480,
            'minWidth' => 200,
            'maxWidth' => 1200,
            'fileDir' => 'diagrams',
        ],
        'html' => [
            'width' => 640,
            'height' => 400,
            'iframeWidth' => '100%',
            'defaultUrl' => 'https://blog.yllemo.com',
            'fileDir' => 'html',
            'fileExt' => 'html',
            'minWidth' => 200,
            'maxWidth' => 1400,
            'minHeight' => 120,
            'maxHeight' => 1200,
        ],
        'promptbook' => [
            'width' => 420,
            'height' => 360,
            'fileDir' => 'promptbook',
            'fileExt' => 'json',
            'minWidth' => 280,
            'maxWidth' => 900,
            'minHeight' => 200,
            'maxHeight' => 800,
        ],
        'archicode' => [
            'width' => 520,
            'height' => 480,
            'minWidth' => 200,
            'maxWidth' => 1400,
            'minHeight' => 280,
            'maxHeight' => 1200,
            'fileDir' => 'diagrams',
            'fileExt' => 'ac',
        ],
        'taxonomi' => [
            'width' => 520,
            'minWidth' => 200,
            'maxWidth' => 1200,
            'minHeight' => 120,
            'maxHeight' => 1200,
            'fileDir' => 'taxonomi',
            'fileExt' => 'md',
        ],
        'mindmap' => [
            'width' => 520,
            'minWidth' => 200,
            'maxWidth' => 1200,
            'fileDir' => 'mindmap',
            'fileExt' => 'md',
        ],
        'svg' => [
            'width' => 480,
            'minWidth' => 160,
            'maxWidth' => 1200,
            'fileDir' => 'svg',
            'fileExt' => 'svg',
        ],
        'annotation' => [
            'width' => 320,
            'height' => 160,
            'minWidth' => 120,
            'maxWidth' => 800,
            'minHeight' => 80,
            'maxHeight' => 400,
            'tipX' => 300,
            'tipY' => 120,
            'dir' => 'ne',
            'arrowStyle' => 'curve',
            'arrowLen' => 90,
            'rotation' => 0,
            'color' => '#F5A623',
            'fontSize' => 26,
            'strokeWidth' => 2.5,
            'fontFamily' => "'Caveat', cursive",
        ],
    ],

    'modules' => [
        'markdown' => [
            'addTitle' => 'Lägg till Markdown',
            'editTitle' => 'Redigera Markdown',
            'okLabel' => 'Spara',
            'addToast' => 'Markdown-nod tillagd',
            'editToast' => 'Sparad',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd (px)',
                'height' => 'Höjd (px)',
                'heightHint' => 'Standard 600 px — kan även ändras genom att dra i kortets hörn.',
                'content' => 'Markdown-innehåll',
            ],
            'placeholders' => [
                'title' => 'Rubrik för handtaget…',
                'height' => '600',
                'content' => "## Rubrik\n\nText, **fetstil**, _kursiv_, listor, tabeller…",
            ],
            'editorUrl' => 'html/markdown.php',
            'fullscreenLabel' => 'Fullskärmseditor',
            'fullscreenTitle' => 'Markdown — fullskärmseditor',
            'docxLabel' => 'Importera DOCX',
            'docxTitle' => 'Konvertera Word-dokument till Markdown med bilder',
        ],
        'bild' => [
            'addTitle' => 'Lägg till Bild',
            'editTitle' => 'Redigera Bild',
            'okLabel' => 'Spara',
            'addToast' => 'Bildnod tillagd',
            'editToast' => 'Sparad',
            'missingToast' => 'Välj en bild, klistra in (Ctrl+V) eller ange en URL',
            'pasteToast' => 'Bild klistrad från urklipp',
            'paintEditorUrl' => 'html/paint-skill-editor.php',
            'paintLabel' => 'Måla / redigera bild',
            'paintTitle' => 'Öppna bilden i målarprogrammet',
            'paintSaveToast' => 'Bild uppdaterad från målaren',
            'labels' => [
                'upload' => 'Ladda upp bild',
                'pasteHint' => 'Ctrl+V klistrar in bild från urklipp',
                'url' => '— eller — Extern URL',
                'caption' => 'Bildtext (caption)',
                'alt' => 'Alt-text',
                'width' => 'Bredd (px)',
                'replace' => 'Byt bild (valfri)',
                'paintHint' => 'Knappen nere till vänster öppnar målaren (ny tom canvas eller redigera vald bild).',
            ],
            'placeholders' => [
                'upload' => 'Klicka eller dra en bild hit',
                'url' => 'https://…',
                'caption' => 'Valfri bildtext',
                'alt' => 'Beskrivning av bilden',
                'replace' => 'Välj ny bild',
            ],
        ],
        'mermaid' => [
            'addTitle' => 'Lägg till Mermaid-diagram',
            'editTitle' => 'Redigera Mermaid',
            'okLabel' => 'Spara',
            'addToast' => 'Mermaid-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/mermaid-editor.php',
            'fullscreenLabel' => 'Mermaid-editor',
            'fullscreenTitle' => 'Monaco-editor med live-förhandsvisning och exempeldiagram',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'height' => 'Höjd kort (px)',
                'heightHint' => 'Standard 600 px — kan även ändras genom att dra i kortets hörn.',
                'content' => 'Mermaid-kod',
                'editorHint' => 'Tips: öppna Mermaid-editorn (knapp nere till vänster) för Monaco, live-förhandsvisning, exempeldiagram och export.',
            ],
            'placeholders' => [
                'title' => 'Diagramtitel…',
                'height' => '600',
                'content' => "flowchart LR\n  A[Start] --> B[Slut]",
            ],
        ],
        'plantuml' => [
            'addTitle' => 'Lägg till PlantUML-diagram',
            'editTitle' => 'Redigera PlantUML',
            'okLabel' => 'Spara',
            'addToast' => 'PlantUML-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/plantuml-editor.php',
            'fullscreenLabel' => 'PlantUML-editor',
            'fullscreenTitle' => 'Monaco-editor med live-förhandsvisning och PNG-export',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'height' => 'Höjd kort (px)',
                'heightHint' => 'Standard 600 px — kan även ändras genom att dra i kortets hörn.',
                'content' => 'PlantUML-kod',
                'editorHint' => 'Tips: öppna PlantUML-editorn (knapp nere till vänster) för Monaco, live-förhandsvisning och PNG-förhandsbild på kortet.',
            ],
            'placeholders' => [
                'title' => 'Diagramtitel…',
                'height' => '600',
                'content' => "@startuml\nAlice -> Bob: Hej\n@enduml",
            ],
        ],
        'archicode' => [
            'addTitle' => 'Lägg till ArchiCode-diagram',
            'editTitle' => 'Redigera ArchiCode',
            'okLabel' => 'Spara',
            'addToast' => 'ArchiCode-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/archicode.php',
            'libUrl' => 'https://cdn.jsdelivr.net/gh/yllemo/ArchiCode@latest/archicode.js',
            'cssUrl' => 'https://cdn.jsdelivr.net/gh/yllemo/ArchiCode@latest/archicode.css',
            'fullscreenLabel' => 'ArchiCode-editor',
            'fullscreenTitle' => 'Monaco-editor med live-förhandsvisning och SVG-export',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'height' => 'Höjd kort (px)',
                'heightHint' => 'Standard 480 px — kan även ändras genom att dra i kortets hörn.',
                'content' => 'ArchiCode-kod',
                'editorHint' => 'Tips: öppna ArchiCode-editorn (knapp nere till vänster) för Monaco och live-förhandsvisning. Kortet renderar diagrammet direkt från källkoden.',
            ],
            'placeholders' => [
                'title' => 'Diagramtitel…',
                'height' => '480',
                'content' => '[<business:actor> Kund] -> [<business:process> Order]',
            ],
        ],
        'taxonomi' => [
            'addTitle' => 'Lägg till Taxonomi',
            'editTitle' => 'Redigera Taxonomi',
            'okLabel' => 'Spara',
            'addToast' => 'Taxonomi-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/taxonomi-editor.php',
            'fullscreenLabel' => 'Taxonomi-editor',
            'fullscreenTitle' => 'Visualisering, färger och Monaco-redigering',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'height' => 'Höjd (px)',
                'heightHint' => 'Tomt = automatisk höjd. Ange px för fast höjd — kan även ändras genom att dra i kortets hörn.',
                'content' => 'Markdown (punktlista)',
                'editorHint' => 'Tips: öppna Taxonomi-editorn (knapp nere till vänster) för visualisering och PNG-förhandsbild på kortet.',
            ],
            'placeholders' => [
                'title' => 'Taxonomins titel…',
                'height' => 'Automatisk',
                'content' => "- Verksamhet\n  - HR\n  - IT",
            ],
        ],
        'mindmap' => [
            'addTitle' => 'Lägg till Mindmap',
            'editTitle' => 'Redigera Mindmap',
            'okLabel' => 'Spara',
            'addToast' => 'Mindmap-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/mindmap-editor.php',
            'fullscreenLabel' => 'Mindmap-editor',
            'fullscreenTitle' => 'Interaktiv tankekarta med export',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'content' => 'Markdown-kod',
                'editorHint' => 'Tips: öppna Mindmap-editorn (knapp nere till vänster) för interaktiv redigering och PNG-förhandsbild på kortet.',
            ],
            'placeholders' => [
                'title' => 'Tankekartans titel…',
                'content' => "# Rot\n\n- Gren 1\n  - Undergren",
            ],
        ],
        'svg' => [
            'addTitle' => 'Lägg till SVG',
            'editTitle' => 'Redigera SVG',
            'okLabel' => 'Spara',
            'addToast' => 'SVG-nod tillagd',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/svg-editor.php',
            'fullscreenLabel' => 'SVG Studio',
            'fullscreenTitle' => 'Monaco-editor med live-förhandsvisning och städverktyg',
            'labels' => [
                'title' => 'Titel',
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd kort (px)',
                'content' => 'SVG-kod',
                'editorHint' => 'Tips: öppna SVG Studio (knapp nere till vänster) för Monaco och live-förhandsvisning. Kortet renderar SVG direkt från källkoden.',
            ],
            'placeholders' => [
                'title' => 'SVG-titel…',
                'content' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 260">…</svg>',
            ],
        ],
        'label' => [
            'addTitle' => 'Lägg till Label',
            'editTitle' => 'Redigera Label',
            'okLabel' => 'Spara',
            'addToast' => 'Label tillagd',
            'editToast' => 'Sparad',
            'missingToast' => 'Skriv in en text',
            'labels' => [
                'content' => 'Text',
                'fontSize' => 'Teckenstorlek (px)',
                'color' => 'Färg',
                'widthOptional' => 'Bredd (px, valfri)',
                'linkHint' => 'På canvas: [Hej](https://…) visas som «Hej». Här redigerar du hela markdown-länken.',
            ],
            'placeholders' => [
                'content' => 'Rubrik eller rubriktext…',
                'width' => 'auto',
            ],
        ],
        'drawio' => [
            'addTitle' => 'Lägg till Draw.io',
            'editTitle' => 'Draw.io — titel',
            'okLabel' => 'Skapa',
            'addToast' => 'Draw.io-nod tillagd',
            'saveToast' => 'Diagram sparat',
            'editorUrl' => 'html/drawio-skill-editor.php',
            'labels' => [
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd på kort (px)',
                'addHint' => 'Draw.io öppnas direkt efter att noden skapats.',
                'editHint' => 'Diagrammet redigeras i draw.io.',
            ],
            'placeholders' => [
                'title' => 'Diagramtitel…',
            ],
        ],
        'bpmn' => [
            'addTitle' => 'Lägg till BPMN',
            'editTitle' => 'BPMN — titel',
            'okLabel' => 'Skapa',
            'addToast' => 'BPMN-nod tillagd',
            'saveToast' => 'BPMN-diagram sparat',
            'editorUrl' => 'html/bpmn-skill-editor.php',
            'labels' => [
                'titleOptional' => 'Titel (valfri)',
                'width' => 'Bredd på kort (px)',
                'addHint' => 'BPMN-editorn öppnas direkt efter att noden skapats.',
                'editHint' => 'Diagrammet redigeras i BPMN-editorn.',
            ],
            'placeholders' => [
                'title' => 'Processtitel…',
            ],
        ],
        'html' => [
            'addTitle' => 'Lägg till HTML / iframe',
            'editTitle' => 'Redigera HTML / iframe',
            'okLabel' => 'Spara',
            'addToast' => 'HTML/iframe-nod tillagd',
            'editToast' => 'Sparad',
            'missingUrlToast' => 'Ange en giltig Website URL (https://…)',
            'missingContentToast' => 'Ange HTML-kod',
            'missingFilenameToast' => 'Ange ett filnamn (t.ex. min-sida)',
            'fileExistsToast' => 'Filnamnet finns redan i paketet',
            'copyCodeLabel' => 'Kopiera iframe-kod',
            'copyToast' => 'iframe-kod kopierad',
            'starterHtml' => '<!DOCTYPE html>
<html lang="sv">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Skill HTML</title>
</head>
<body>
  <h1>Hej!</h1>
  <p>Redigera HTML — filen sparas i skill-paketet som html/…</p>
</body>
</html>',
            'labels' => [
                'titleOptional' => 'Titel (valfri)',
                'title' => 'Titel',
                'source' => 'Källa',
                'tabIframe' => 'iFrame',
                'tabHtml' => 'HTML',
                'url' => 'Website URL',
                'urlHint' => 'Extern sida inbäddad via iframe.',
                'fileName' => 'Filnamn',
                'htmlContent' => 'HTML-kod',
                'fileHint' => 'Visas i iframe på canvas — samma som extern URL.',
                'displaySection' => 'Visning på canvas',
                'iframeHeight' => 'Höjd (px)',
                'cardWidth' => 'Bredd kort (px)',
                'iframeCode' => 'iframe-kod',
            ],
            'placeholders' => [
                'title' => 'Visas i nodhandtaget…',
                'url' => 'https://blog.yllemo.com',
                'fileName' => 'min-sida',
            ],
        ],
        'promptbook' => [
            'addTitle' => 'Lägg till PromptBook',
            'editTitle' => 'Redigera PromptBook',
            'okLabel' => 'Skapa kort',
            'addToast' => 'PromptBook-kort tillagt',
            'saveToast' => 'PromptBook sparat',
            'editToast' => 'Sparad',
            'editorUrl' => 'html/promptbook.php',
            'labels' => [
                'titleOptional' => 'Titel (valfri)',
                'title' => 'Titel',
                'width' => 'Bredd kort (px)',
                'height' => 'Höjd kort (px)',
                'addHint' => 'Fullskärmseditorn öppnas direkt — där redigerar du prompt, testar chatt och LLM-inställningar.',
                'editHint' => 'Fullskärmseditorn öppnas — prompt och LLM redigeras där, inte på kortet.',
            ],
            'placeholders' => [
                'title' => 'Visas i nodhandtaget…',
            ],
        ],
        'annotation' => [
            'addTitle' => 'Lägg till Annotation',
            'editTitle' => 'Redigera Annotation',
            'okLabel' => 'Spara',
            'addToast' => 'Annotation tillagd',
            'editToast' => 'Sparad',
            'labels' => [
                'previewHint' => 'Klicka i förhandsvisningen för att placera pilens spets',
                'text' => 'Text',
                'textPlaceholder' => 'Förklaringstext…',
                'direction' => 'Pil-riktning',
                'arrowStyle' => 'Pilform',
                'font' => 'Textstil',
                'fontSize' => 'Textstorlek',
                'strokeWidth' => 'Pilbredd',
                'arrowLen' => 'Pilens längd',
                'rotation' => 'Rotation',
                'width' => 'Bredd på canvas (px)',
                'height' => 'Höjd på canvas (px)',
                'color' => 'Färg',
                'customColor' => 'Valfri färg',
            ],
            'directions' => [
                ['value' => 'ne', 'label' => '↗ Upp-höger'],
                ['value' => 'nw', 'label' => '↖ Upp-vänster'],
                ['value' => 'se', 'label' => '↘ Ned-höger'],
                ['value' => 'sw', 'label' => '↙ Ned-vänster'],
            ],
            'arrowStyles' => [
                ['value' => 'curve', 'label' => 'Böjd (organisk)'],
                ['value' => 'straight', 'label' => 'Rak'],
                ['value' => 'swoosh', 'label' => 'Swoosh (U-böj)'],
                ['value' => 'scribble', 'label' => 'Handritad (skiss)'],
            ],
            'fonts' => [
                ['value' => "'Caveat', cursive", 'label' => 'Handskrift (Caveat)'],
                ['value' => "'Kalam', cursive", 'label' => 'Kalam'],
                ['value' => 'Arial, Helvetica, sans-serif', 'label' => 'Sans-serif'],
                ['value' => "'Courier New', monospace", 'label' => 'Monospace'],
            ],
            'colors' => [
                ['label' => 'Amber', 'value' => '#F5A623'],
                ['label' => 'Blå', 'value' => '#4A90D9'],
                ['label' => 'Grön', 'value' => '#7ED321'],
                ['label' => 'Röd', 'value' => '#E24B4A'],
                ['label' => 'Lila', 'value' => '#BD10E0'],
                ['label' => 'Vit', 'value' => '#F8F8F8'],
                ['label' => 'Mörk', 'value' => '#1A1A2E'],
                ['label' => 'Teal', 'value' => '#50E3C2'],
            ],
        ],
        'notes' => [
            'addTitle' => 'Lägg till Note',
            'okLabel' => 'Skapa',
            'addToast' => 'Note tillagd',
            'placeholder' => 'Skriv här…',
            'labels' => [
                'color' => 'Färg',
                'width' => 'Bredd (px)',
                'hint' => 'Texten redigeras direkt på noten efter att du skapat den.',
            ],
            'colors' => [
                ['label' => 'Gul', 'value' => '#fff9a8'],
                ['label' => 'Rosa', 'value' => '#ffd4e5'],
                ['label' => 'Blå', 'value' => '#cce5ff'],
                ['label' => 'Grön', 'value' => '#d4f4dd'],
                ['label' => 'Orange', 'value' => '#ffe0b2'],
                ['label' => 'Lila', 'value' => '#e8d4ff'],
            ],
        ],
    ],
];
